### ISSUE TITLE
css属性设置为百分比时

### ISSUE THREAD

**Issue by zhanzizhen** [zhanzizhen/css-note#16]
## margin和padding

当margin和padding的值设置为百分比时，是指相对于最近的块级父元素width（非总宽度）的相应百分比的值，即使是margin-top、margin-bottom、padding-top、padding-bottom，设置为百分比时也是以最近块级父元素的width（非总宽度）为基准，而非height。

## width
元素的width的百分比设置： 定义基于包含块（父元素）宽度的百分比宽度。 话虽如此，实际上无论怎么设置盒模型(box-sizing)的宽度，子元素都是基于父元素的内容（content）宽度并非width的实际大小。

使用width:100%的时候 也要注意其基准点到底是谁：

（1）对于使用position:relative的子元素或浮动的子元素,其基准点始终是基于其直接父元素而言的，跟其父元素是否有定位无关。

（2）对于绝对定位position:absolute的子元素，其基准点是相对于离其最近的一层定位父元素而言。如果其所有父级元素均无定位，则是相对于body而言。

（3）对于使用position:fixed的子元素，其基准点就是body。跟父元素无关。

## height

值 | 描述
-- | --
auto | 默认。浏览器会计算出实际的高度。
length | 使用 px、cm 等单位定义高度。
% | 基于包含它的块级对象的百分比高度。
inherit | 规定应该从父元素继承 height 属性的值。

当父元素没有设置固定height值时，子元素得百分比height无效

**Comment by zhanzizhen** [comment]
利用padding百分比的特性，我们可以让盒子的宽度等于其高度

```html
<div class='box'></div>
```

```css
 .box{
    width: 62%;
    display: block;
    margin: 0 auto 6px;
    padding-top: 62%;
    position: relative;
}
```

常用到的场景有很多，比如让图片始终保持1:1

```html
<div class='box'><img src="xxx" /></div>
```

```css
.box>img{
width: 100%;
    height: 100%;
    position: absolute;
    left: 0;
    top: 0;
}
```
