### ISSUE TITLE
less一些很有用的技巧

### ISSUE THREAD

**Issue by zhanzizhen** [zhanzizhen/css-note#2]
Properties as Variables (NEW!)
v3.0.0

You can easily treat properties like variables using the $prop syntax. Sometimes this can make your code a little lighter.

```less
.widget {
color: #efefef;
background-color: $color;
}
Compiles to:

.widget {
color: #efefef;
background-color: #efefef;
}
```

**Comment by zhanzizhen** [comment]
![image](https://user-images.githubusercontent.com/22932241/80464746-d1f21d00-896c-11ea-8151-63b33cc40286.png)

**Comment by zhanzizhen** [comment]
![image](https://user-images.githubusercontent.com/22932241/80464778-df0f0c00-896c-11ea-87dd-449e40f2ae75.png)

**Comment by zhanzizhen** [comment]
![image](https://user-images.githubusercontent.com/22932241/80464837-efbf8200-896c-11ea-9cc6-b653a5cf7c85.png)

**Comment by zhanzizhen** [comment]
![image](https://user-images.githubusercontent.com/22932241/80464870-fd750780-896c-11ea-8cf9-116f033c9aad.png)

**Comment by zhanzizhen** [comment]
```less
.CampaignButton {
  background-image: url('../../images/button.png');
  @media (min-width: 750px) {
    &:not(&--disabled):hover {
      background-image: url('../../images/button-hover.png');
      cursor: pointer;
    }
  }
  &--disabled {
    background-image: url('../../images/button-disabled.png');
    cursor: unset;
  }
}
```

**Comment by zhanzizhen** [comment]
```less
      .championLine {
        padding-top: 12px;
        &::before {
          // less支持这样写，太棒了
          top: 22px + $padding-top;
          border-radius: 50%;
        }
      }
```
