### ISSUE TITLE
内联元素、margin auto的原理

### ISSUE THREAD

**Issue by zhanzizhen** [zhanzizhen/css-note#3]
### 内联元素

内联元素不能设置width和height，并且padding和margin只有水平方向的有作用。为什么？因为内联元素的设计目标本是如此，设计者希望内联元素是被动的，只会被内容撑开。下面是[w3c](https://www.w3.org/TR/CSS2/visudet.html#Computing_heights_and_margins)对它的描述：

> ### 10.6.1 Inline, non-replaced elements
>
> The ['height'](https://www.w3.org/TR/CSS2/visudet.html#propdef-height) property does not apply. The height of the content area should be based on the font, but this specification does not specify how. A UA may, e.g., use the em-box or the maximum ascender and descender of the font. (The latter would ensure that glyphs with parts above or below the em-box still fall within the content area, but leads to differently sized boxes for different fonts; the former would ensure authors can control background styling relative to the 'line-height', but leads to glyphs painting outside their content area.)

### replaced element & non-replaced element

元素除了可以分成内联和块状。还可以从另一角度，分成替换元素和不可替换元素。替换元素一般有内在尺寸，所以具有width和height，可以设定。例如你不指定img的width和height时，就按其内在尺寸显示，也就是图片被保存的时候的宽度和高度。对于表单元素，浏览器也有默认的样式，包括宽度和高度。常见的替换元素如：`<img>、<input>、<textarea>、<select>`。这四个常见的元素，同时也是内联元素。

### 强大的margin: auto

auto的意思是让浏览器自动计算。

常见的是利用它来水平居中：

```css
div.child{
    width:100px;
    margin:0 auto;
}
```

为什么内联元素的margin: 0 auto;无效呢？因为内联元素的左右没有剩余空间，所以左右的auto其实就相当于0。

上面的例子换种写法，尝试利用margin auto来垂直居中：

```css
.father{
    width:400px;
    height:400px;
}
div.child{
    width:100px;
    height:100px;
    margin: auto;
}
```

可以看到是无效的。为啥？

首先，这是w3c规定的：

> ### 10.6.2 Inline replaced elements, block-level replaced elements in normal flow, 'inline-block' replaced elements in normal flow and floating replaced elements
>
> If ['margin-top'](https://www.w3.org/TR/CSS21/box.html#propdef-margin-top), or ['margin-bottom'](https://www.w3.org/TR/CSS21/box.html#propdef-margin-bottom) are 'auto', their used value is 0.

可以看到，在**正常流(static定位)**中，如果margin-top或者margin-bottom是auto的话，它们都会被当作0来计算。

为啥w3c要这么设置？

因为元素的堆叠是从左到右，从上到下。如果你的上述的child有两个，其中一个设置了margin: auto，另一个不设置。那么浏览器该如何处理？如果浏览器设置了第一个child是上下居中，那么第二个盒子是在顶部的。这样从水平方向看，这两个盒子的站位显然破坏了浏览器“从左到右”的布局模型。所以，为了规范起见，在正常流中，上下margin的auto都是0。

那么，absolute和fixed可以设置margin auto吗，可以的，但要加上top: 0;bottom:0;

```css
.child{
    margin: auto;
    position:absolute;
        top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    width:100px;
    height:100px;
}
```

具体原因有待继续研究。

在flex中，margin auto vertical也是能起作用的。margin auto的用处经常有：

1. 设置单个子元素的上下垂直居中：

```css
.father{
    display:flex;
}
.child{
    margin: auto;
}
```

2. 让某个子元素“往右靠”。

```css
.father{
    display:flex;
}
.child:last-child{
    margin-left: auto;
}
```

https://juejin.im/post/5a1b7319f265da43333e1d60

https://blog.csdn.net/linshizhan/article/details/71521140

https://www.w3.org/TR/CSS2/visudet.html#Computing_heights_and_margins

https://stackoverflow.com/questions/34552116/why-doesnt-margin-auto-center-an-element-vertically/34552175
